var Components = require('../components.json')
var fs = require('fs')
var path = require('path')
var OUTPUT_PATH = path.join(__dirname, '../src/components.js')
var IMPORT_TEMPLATE = 'import {{name}} from \'../packages/{{package}}\''
var INSTALL_COMPONENT_TEMPLATE = '  Vue.component({{name}}.name, {{name}})'
var MAIN_TEMPLATE = `
/* Automatic generated by './scripts/build-entry.js' */

{{include}}

const install = function (Vue, opts = {}) {
  if (install.installed) return

{{install}}
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

module.exports = {
  version: '{{version}}',
  install,
{{list}}
}
`

var ComponentNames = Object.keys(Components)
var uppercamelcase = name => name.replace(/[_.\- ]+(\w|$)/g, (m, p1) => p1.toUpperCase())
var render = (tpl, model) => tpl.replace(/{{(\w+)}}/g, (m, key) => model[`${key}`])

var includeComponentTemplate = []
var installTemplate = []
var listTemplate = []

ComponentNames.forEach(name => {
  var componentName = uppercamelcase(name)

  includeComponentTemplate.push(render(IMPORT_TEMPLATE, {
    name: componentName,
    package: name
  }))

  if (['Loading', 'MessageBox', 'Notification', 'Message'].indexOf(componentName) === -1) {
    installTemplate.push(render(INSTALL_COMPONENT_TEMPLATE, {
      name: componentName,
      component: name
    }))
  }

  if (componentName !== 'Loading') listTemplate.push(`  ${componentName}`)
})

var template = render(MAIN_TEMPLATE, {
  include: includeComponentTemplate.join('\n'),
  install: installTemplate.join('\n'),
  version: process.env.VERSION || require('../package.json').version,
  list: listTemplate.join(',\n')
})

fs.writeFileSync(OUTPUT_PATH, template)
console.log('[build entry] DONE:', OUTPUT_PATH)
