
/* Automatic generated by './scripts/build-entry.js' */

import iImgUpload from '../packages/iImgUpload'

const install = function (Vue, opts = {}) {
  if (install.installed) return

  Vue.component(iImgUpload.name, iImgUpload)
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

module.exports = {
  version: '0.1.3',
  install,
  iImgUpload
}
